version: '2'
services:
    black_tom-db:
        image: postgres:11.1
        network_mode: bridge
        environment:
            POSTGRES_DB: "black_tom"
            POSTGRES_PASSWORD: "${black_tom_DB_PASSWORD}"
            POSTGRES_USER: "${black_tom_DB_USER}"
        volumes:
            - ${black_tom_DB_DATA_PATH}:/var/lib/postgresql/data
        ports:
            - 5435:5432/tcp
    black_tom:
        image: jfrostburke/black_tom:latest
        network_mode: bridge
        links:
            - "black_tom-db:black_tom-db"
        ports:
            - 8889:8080
        restart: "always"
        mem_limit: "4g"
        logging:
            options:
                max-file: "3"
                max-size: "10m"
        environment:
            - DB_NAME=black_tom
            - DB_HOST=black_tom-db
            - DB_PORT=5432
            - black_tom_DB_USER=${black_tom_DB_USER}
            - black_tom_DB_PASSWORD=${black_tom_DB_PASSWORD}
            - black_tom_DB_BACKEND=postgres
            - LCO_APIKEY=${black_tom_LCO_APIKEY}
            - SNEXBOT_APIKEY=${black_tom_SNEXBOT_APIKEY}
            - AWS_ACCESS_KEY_ID=${black_tom_AWS_ACCESS_KEY_ID}
            - AWS_S3_REGION_NAME=${black_tom_AWS_REGION_NAME}
            - AWS_SECRET_ACCESS_KEY=${black_tom_AWS_SECRET_ACCESS_KEY}
            - AWS_STORAGE_BUCKET_NAME=${black_tom_AWS_STORAGE_BUCKET_NAME}
            - TWITTER_APIKEY=${black_tom_TWITTER_APIKEY}
            - TWITTER_SECRET=${black_tom_TWITTER_SECRET}
            - TWITTER_ACCESSTOKEN=${black_tom_TWITTER_ACCESSTOKEN}
            - TWITTER_ACCESSSECRET=${black_tom_TWITTER_ACCESSSECRET}
            - GEMINI_PROGRAMID=${black_tom_GEMINI_PROGRAMID}
            - GEMINI_EMAIL=${black_tom_GEMINI_EMAIL}
            - GEMINI_PASSWORD=${black_tom_GEMINI_PASSWORD}
            - GEMINI_SERVER=${black_tom_GEMINI_SERVER}
