# Generated by Django 2.2.6 on 2019-10-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tnstarget',
            options={'get_latest_by': ('-name',), 'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='tnstarget',
            name='jdlastobs',
            field=models.FloatField(blank=True, help_text='JD of the last datapoint', null=True, verbose_name='JD last observation'),
        ),
    ]
